services:
  recorder:
    image: cs2-recorder:prod
    build:
      context: .
      dockerfile: Test.Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - cs2-data:/home/steam/cs2
    privileged: true
    secrets:
      - steam_username
      - steam_pass
    cpus: 8
    mem_limit: 16g
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    shm_size: 1g
    tty: true

volumes:
  cs2-data:

secrets:
  steam_username:
    file: ./steam_username.txt
  steam_pass:
    file: ./steam_pass.txt
